services:
  wik-dps-tp01:
    build: .
    image: wik-dps-tp01
    deploy:
      replicas: 4
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Vérifie que ce fichier existe à cet emplacement
    ports:
    - "8080:80"
    networks:
    - app-network


networks:
  app-network:
    driver: bridge