services:
  wik-dps-tp01:
    build: .
    image: wik-dps-tp01
    deploy:
      replicas: 4
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    networks:
      - app-network

  wordpress:
    image: wordpress:latest
    deploy:
      replicas: 2
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_REDIS_HOST: redis
    volumes:
      - wp_data:/var/www/html
    networks:
      - app-network

volumes:
  db_data:
  wp_data:

networks:
  app-network:
    driver: bridge
